# Copyright Â© 2022-2023, SAS Institute Inc., Cary, NC, USA. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# default PG System settings we will set if the user does
# not define their own values
postgres_system_setting_max_prepared_transactions: "1024"
postgres_system_setting_max_connections: "1024"