# Copyright Â© 2022-2024, SAS Institute Inc., Cary, NC, USA. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

---
- name: Create kubernetes /etc/kubernetes/pki directory
  ansible.builtin.file:
    path: /etc/kubernetes/{{ item }}
    state: directory
    mode: "0755"
    owner: root
    group: root
  with_items:
    - pki
    - pki/etcd
  tags:
    - install
    - update

- name: Copy Kubernetes primary control plane PKI files to secondary control plane k8s_nodes
  ansible.posix.synchronize:
    src: /etc/kubernetes/pki/{{ item }}
    dest: /etc/kubernetes/pki/{{ item }}
  delegate_to: "{{ groups['k8s_control_plane'][0] }}"
  with_items:
    - ca.crt
    - ca.key
    - sa.key
    - sa.pub
    - front-proxy-ca.crt
    - front-proxy-ca.key
    - etcd/ca.crt
    - etcd/ca.key
  tags:
    - install

- name: Generate control plane join token
  ansible.builtin.command: kubeadm token create --print-join-command
  register: kubeadm_join_cmd
  delegate_to: "{{ groups['k8s_control_plane'][0] }}"
  tags:
    - install

- name: Extract token and ca-cert-hash from join command
  ansible.builtin.set_fact:
    join_token: "{{ kubeadm_join_cmd.stdout.split()[4] }}"
    join_ca_hash: "{{ kubeadm_join_cmd.stdout.split()[6] }}"
  tags:
    - install

- name: Join secondary control plane nodes to the cluster using VIP
  ansible.builtin.command: "kubeadm join {{ kubernetes_vip_ip }}:6443 --token {{ join_token }} --discovery-token-ca-cert-hash {{ join_ca_hash }} --control-plane"
  tags:
    - install
