---
- name: Create kubernetes /etc/kubernetes/pki directory
  ansible.builtin.file:
    path: /etc/kubernetes/{{ item }}
    state: directory
    mode: '0755'
    owner: root
    group: root
  with_items:
    - pki
    - pki/etcd
  tags:
    - install
    - update

- name: Copy Kubernetes primary control plane PKI files to secondary control plane k8s_nodes
  ansible.posix.synchronize: 
    src: /etc/kubernetes/pki/{{ item }}
    dest: /etc/kubernetes/pki/{{ item }}
  delegate_to: "{{groups['k8s_control_plane'][0]}}"
  with_items:
    - ca.crt
    - ca.key
    - sa.key
    - sa.pub
    - front-proxy-ca.crt
    - front-proxy-ca.key
    - etcd/ca.crt
    - etcd/ca.key
  tags:
    - install

- name: Generate control plane join command
  ansible.builtin.shell: kubeadm token create --print-join-command
  register: kubeadm_join_cmd
  delegate_to: "{{groups['k8s_control_plane'][0]}}"
  tags:
    - install

- name: Join secondary control plane nodes to the cluster
  ansible.builtin.shell: "{{ kubeadm_join_cmd.stdout }} --control-plane"
  tags:
    - install
