# Copyright Â© 2022-2024, SAS Institute Inc., Cary, NC, USA. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

---
# NOTE: The usage and setting of the iac_inventory_dir variable
#       is only needed given this task is run on localhost
#       an implied localhost and this keeps the magic inventory_file
#       and inventory_dir from having values.
#
#       Reference URL : https://docs.ansible.com/ansible/latest/inventory/implicit_localhost.html
#
- name: Cleaning up old sig-storage-local-static-provisioner repo
  ansible.builtin.file:
    path: "/tmp/{{ kubernetes_LOCAL_VOLUME_NAME }}"
    state: absent
  tags:
    - install
    - update

- name: Cloning sig-storage-local-static-provisioner
  ansible.builtin.git:
    repo: "{{ kubernetes_LOCAL_VOLUME_REPO }}"
    dest: "/tmp/{{ kubernetes_LOCAL_VOLUME_NAME }}"
    version: "{{ kubernetes_LOCAL_VOLUME_REPO_VERSION }}"
  tags:
    - install
    - update

- name: Setting up local storage for the cluster using sig-storage-local-static-provisioner
  kubernetes.core.helm:
    name: "{{ kubernetes_LOCAL_VOLUME_NAME }}"
    namespace: "{{ kubernetes_LOCAL_VOLUME_NAMESPACE }}"
    chart_ref: "{{ kubernetes_LOCAL_VOLUME_REPO_LOCATION }}/helm/provisioner"
    chart_version: "{{ kubernetes_LOCAL_VOLUME_CHART_VERSION }}"
    values: "{{ kubernetes_LOCAL_VOLUME_CONFIG }}"
    kubeconfig: "{{ iac_inventory_dir }}/{{ kubernetes_cluster_name }}-kubeconfig.conf"
    create_namespace: true
    wait: true
  tags:
    - install
    - update

- name: Remove sig-storage-local-static-provisioner
  kubernetes.core.helm:
    name: "{{ kubernetes_LOCAL_VOLUME_NAME }}"
    namespace: "{{ kubernetes_LOCAL_VOLUME_NAMESPACE }}"
    kubeconfig: "{{ iac_inventory_dir }}/{{ kubernetes_cluster_name }}-kubeconfig.conf"
    wait: true
    state: absent
  tags:
    - uninstall
