---
# NOTE: The usage and setting of the iac_inventory_dir variable
#       is only needed given this task is run on localhost
#       an implied localhost and this keeps the magic inventory_file
#       and inventory_dir from having values.
#
#       Reference URL : https://docs.ansible.com/ansible/latest/inventory/implicit_localhost.html
#
- name: Cloning sig-storage-local-static-provisioner
  ansible.builtin.git:
    repo: "{{ LOCAL_VOLUME_REPO }}"
    dest: "/tmp/{{ LOCAL_VOLUME_NAME }}"
    version: "{{ LOCAL_VOLUME_REPO_VERSION }}"
  tags:
    - install
    - update

- name: Setting up default storage for cluster using sig-storage-local-static-provisioner 
  kubernetes.core.helm:
    name: "{{ LOCAL_VOLUME_NAME }}"
    namespace: "{{ LOCAL_VOLUME_NAMESPACE }}"
    chart_ref: "{{ LOCAL_VOLUME_REPO_LOCATION }}/helm/provisioner"
    chart_version: "{{ LOCAL_VOLUME_CHART_VERSION }}"
    values: "{{ LOCAL_VOLUME_CONFIG }}"
    kubeconfig: "{{ iac_inventory_dir }}/{{ kubernetes_cluster_name }}-kubeconfig.conf"
    create_namespace: true
    wait: true
  tags:
    - install
    - update

- name: Remove sig-storage-local-static-provisioner
  kubernetes.core.helm:
    name: "{{ LOCAL_VOLUME_NAME }}"
    namespace: "{{ LOCAL_VOLUME_NAMESPACE }}"
    kubeconfig: "{{ iac_inventory_dir }}/{{ kubernetes_cluster_name }}-kubeconfig.conf"
    wait: true
    state: absent
  tags:
    - uninstall
