# Copyright Â© 2022-2024, SAS Institute Inc., Cary, NC, USA. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

---
- name: Cleaning up the control plane
  ansible.builtin.shell: |
    kubeadm reset --force
  tags:
    - uninstall
