# Copyright Â© 2022-2024, SAS Institute Inc., Cary, NC, USA. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

---
- name: Copy kube-vip manifest to secondary control planes
  ansible.posix.synchronize:
    src: /etc/kubernetes/manifests/kube-vip.yaml
    dest: /etc/kubernetes/manifests/kube-vip.yaml
  delegate_to: "{{ groups['k8s_control_plane'][0] }}"
  tags:
    - install
