# Copyright Â© 2022-2024, SAS Institute Inc., Cary, NC, USA. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

---
## sig-storage-local-static-provisioner
METALLB_NAME: metallb
METALLB_NAMESPACE: kube-system
METALLB_CHART_NAME: metallb
METALLB_CHART_URL: https://metallb.github.io/metallb
METALLB_CHART_VERSION: 0.14.3
METALLB_KUBE_CONFIG: "{{ ansible_env.HOME }}/.kube/config"
METALLB_CONFIG:
  controller:
    tolerations:
      - key: workload.sas.com/class
        operator: Exists
        effect: NoSchedule
  speaker:
    tolerations:
      - key: workload.sas.com/class
        operator: Exists
        effect: NoSchedule
