---
- name: Label/Taints for cluster nodes
  ansible.builtin.shell: |
    kubectl label nodes {{ ansible_hostname }} node-role.kubernetes.io/node= --overwrite
  delegate_to: "{{groups['k8s_control_plane'][0]}}"
  tags:
    - install
    - update
