# Copyright Â© 2022-2024, SAS Institute Inc., Cary, NC, USA. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

---
# Set owner and group for Ubuntu OS
- name: Set owner and group for Ubuntu OS
  ansible.builtin.set_fact:
    owner: nobody
    group: nogroup
  when: ansible_distribution == "Ubuntu" and (ansible_distribution_version == "20.04" or ansible_distribution_version == "22.04")
  tags:
    - install
    - update

- name: Create /mnt/sas/volumes directory
  ansible.builtin.file:
    path: /mnt/sas/volumes
    state: directory
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: "0777"
  ignore_errors: true
  tags:
    - install
    - update
