# Copyright Â© 2022-2024, SAS Institute Inc., Cary, NC, USA. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

---
# Install NFS client utilities required for NFS volume mounting
- name: Install NFS client utilities
  ansible.builtin.package:
    name: nfs-common
    state: present
    update_cache: true
  tags:
    - install
    - update

# Set owner and group for Ubuntu OS
- name: Set owner and group for Ubuntu OS
  ansible.builtin.set_fact:
    owner: nobody
    group: nogroup
  tags:
    - install
    - update

- name: Create /mnt/sas/volumes directory
  ansible.builtin.file:
    path: /mnt/sas/volumes
    state: directory
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: "0777"
  ignore_errors: true
  tags:
    - install
    - update
