# Copyright Â© 2022-2023, SAS Institute Inc., Cary, NC, USA. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

---
#
# Kubernetes Playbook - Installs all elements needed for a stable
#                       kubernetes cluster for use with Viya 4
#

# All systems
- hosts: all
  become: true
  become_user: root
  roles:
    - { role: kubernetes/common }

# All kubernetes nodes
- hosts: k8s
  become: true
  become_user: root
  roles:
    - { role: "kubernetes/cri/{{ kubernetes_cri }}" } # Selection will be made based on the value of kubernetes_cri in your ansible-vars.yaml file
    - { role: kubernetes/toolbox }

# Primary control plane node
- hosts: k8s_control_plane[0]
  become: true
  become_user: root
  roles:
    - { role: kubernetes/vip/primary }                # kube-vip : https://kube-vip.io/docs/installation/static/
    - { role: kubernetes/control_plane/init/primary }
    - { role: "kubernetes/cni/{{ kubernetes_cni }}" } # calico : https://projectcalico.docs.tigera.io/getting-started/kubernetes/self-managed-onprem/onpremises#install-calico-with-kubernetes-api-datastore-50-nodes-or-less

# Secure kubernetes items
- hosts: localhost
  roles:
    - { role: kubernetes/misc }

# Secondary control plane nodes
- hosts: k8s_control_plane[1:]
  become: true
  become_user: root
  roles:
    - { role: kubernetes/control_plane/init/secondary }
    - { role: kubernetes/vip/secondary }

# Compute nodes
- hosts: k8s_node
  become: true
  become_user: root
  roles:
    - { role: kubernetes/node/baseline }
    - { role: kubernetes/node/init }

# Kubernetes loadbalancer
- hosts: k8s_control_plane[0]
  become: true
  become_user: root
  roles:
    - { role: "kubernetes/loadbalancer/{{ kubernetes_loadbalancer }}" }

# Label/Taint Kubernetes nodes
- hosts: k8s
  become: true
  become_user: root
  roles:
    - { role: kubernetes/node/labels_taints }

# Alter PostgreSQL server and add PostgreSQL databases
- hosts: postgres
  become: true
  become_user: postgres
  roles:
    - { role: kubernetes/database/postgres/alter_server_settings }
    - { role: kubernetes/database/postgres/create_databases }

# Restart PostgreSQL server
- hosts: postgres
  become: true
  become_user: root
  roles:
    - { role: kubernetes/database/postgres/restart_server }

# Setup default storage class for cluster
- hosts: localhost
  roles:
    - { role: kubernetes/storage/sig-storage-local-static-provisioner }
    - { role: kubernetes/storage/nfs-subdir-external-provisioner }

# Setup metrics-server for cluster
- hosts: localhost
  roles:
    - { role: kubernetes/metrics/metrics-server }

# Misc cluster related items
- hosts: localhost
  roles:
    - { role: kubernetes/sas-iac-buildinfo }
