---
# Compute nodes
- hosts: k8s_node
  become: true
  become_user: root
  serial: 1
  roles:
    - { role: kubernetes/node/removal }

# Control plane
- hosts: k8s_control_plane
  become: true
  become_user: root
  roles:
    - { role: kubernetes/control_plane/removal }

# Clean up toolbox items
- hosts: k8s
  become: true
  become_user: root
  roles:
    - { role: kubernetes/toolbox }
